"""rooms objects and task templates

Revision ID: 011768255243
Revises: 916e4ffafce3
Create Date: 2026-09-27 16:22:53.506443

"""
from alembic import op
import sqlalchemy as sa


revision = '011768255243'
down_revision = '916e4ffafce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('bedroom', 'bathroom', 'kitchen', 'living', 'dining', 'balcony', 'patio', 'laundry', 'other', name='room_type'), nullable=False),
    sa.Column('floor', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_household_id'), 'rooms', ['household_id'], unique=False)
    op.create_table('room_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai', name='object_source'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_objects_room_id'), 'room_objects', ['room_id'], unique=False)
    op.create_table('task_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('cleaning', 'kitchen', 'laundry', 'bathroom', 'organization', 'outdoor', 'general', name='task_category'), nullable=False),
    sa.Column('base_minutes', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Enum('low', 'medium', 'high', name='effort'), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'once', name='frequency'), nullable=False),
    sa.Column('preferred_weekday', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_household_id'), 'task_templates', ['household_id'], unique=False)
    op.create_table('task_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('extra_minutes', sa.Integer(), nullable=False),
    sa.Column('applies', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_conditions_template_id'), 'task_conditions', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_conditions_template_id'), table_name='task_conditions')
    op.drop_table('task_conditions')
    op.drop_index(op.f('ix_task_templates_household_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_room_objects_room_id'), table_name='room_objects')
    op.drop_table('room_objects')
    op.drop_index(op.f('ix_rooms_household_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
