"""users households members invitations

Revision ID: 916e4ffafce3
Revises: 
Create Date: 2026-09-27 15:55:38.705992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '916e4ffafce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('household_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='member_role'), nullable=False),
    sa.Column('member_type', sa.Enum('adult', 'child', name='member_type'), nullable=False),
    sa.Column('capacity_factor', sa.Float(), nullable=False),
    sa.Column('weekly_minutes', sa.Integer(), nullable=True),
    sa.Column('days_available', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('room_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_member_household_user')
    )
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_members_user_id'), 'household_members', ['user_id'], unique=False)
    op.create_table('household_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('inviter_member_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'used', 'revoked', name='invite_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by_member_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_member_id'], ['household_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_member_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invitations_code'), 'household_invitations', ['code'], unique=True)
    op.create_index(op.f('ix_household_invitations_household_id'), 'household_invitations', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_household_invitations_household_id'), table_name='household_invitations')
    op.drop_index(op.f('ix_household_invitations_code'), table_name='household_invitations')
    op.drop_table('household_invitations')
    op.drop_index(op.f('ix_household_members_user_id'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('households')
    # ### end Alembic commands ###
